/*##############################################################################################
#                                                                                              #
#     #############       #############       #############       ####                ####     #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #     #    #########      #    #####    #     #    #              #    #    #
#    #    #   #    #     #    #              #    #   #    #     #    #              #    #    #
#    #    #####    #     #    #              #    #####    #     #    #              #    #    #
#    #             #     #    #########      #             #     #    #              #    #    #
#    #             #     #             #     #             #     #    #              #    #    #
#    #    #####    #      #########    #     #    #####    #     #    #              #    #    #
#    #    #   #    #              #    #     #    #   #    #     #    #              #    #    #
#    #    #   #    #      #########    #     #    #   #    #     #    #########      #    #    #
#    #    #   #    #     #             #     #    #   #    #     #             #     #    #    #
#     ####     ####       #############       ####     ####       #############       ####     #
#                                                                                              #
#   Department of Energy                                                                       #
#   Politecnico di Milano                                                                      #
#   Author: Stefano Rebughini <stefano.rebughini@polimi.it>                                    #
#                                                                                              #
################################################################################################
#                                                                                              #
#   License                                                                                    #
#                                                                                              #
#   This file is part of ASALI.                                                                #
#                                                                                              #
#   ASALI is free software: you can redistribute it and/or modify                              #
#   it under the terms of the GNU General Public License as published by                       #
#   the Free Software Foundation, either version 3 of the License, or                          #
#   (at your option) any later version.                                                        #
#                                                                                              #
#   ASALI is distributed in the hope that it will be useful,                                   #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of                             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                              #
#   GNU General Public License for more details.                                               #
#                                                                                              #
#   You should have received a copy of the GNU General Public License                          #
#   along with ASALI. If not, see <http://www.gnu.org/licenses/>.                              #
#                                                                                              #
##############################################################################################*/

OpenSMOKE::ThermodynamicsMap_Surface_CHEMKIN<double>*        thermodynamicsSurfaceMapXML;
OpenSMOKE::ThermodynamicsMap_CHEMKIN<double>*                thermodynamicsMapXML;
OpenSMOKE::KineticsMap_CHEMKIN<double>*                        kineticsMapXML;
OpenSMOKE::KineticsMap_Surface_CHEMKIN_Lumped<double>*        kineticsSurfaceMapXML;
OpenSMOKE::TransportPropertiesMap_CHEMKIN<double>*            transportMapXML;
OpenSMOKE::StoichiometricMap*                                stoichiometricMapXML;

OpenSMOKE::OpenSMOKEVectorDouble yF;
OpenSMOKE::OpenSMOKEVectorDouble x0;

OpenSMOKE::OpenSMOKEVectorDouble x0bulk;
OpenSMOKE::OpenSMOKEVectorDouble x0site;

unsigned int NC;
unsigned int NE;
unsigned int SURF_NC;
unsigned int SURF_NP;

double G;
